### ISSUE TITLE
Command about necessary information about the bot 

### ISSUE THREAD

**Issue by CringleySDays** [xp-bot/xp-bot#6]
`/about` command which will display information links about dashboard, account settings, premium, privacy policy

Description about status, top.gg (voting), support server. All of these would be links

Short description about the bot itself 

Footer will display the response time & shard the server is on

**Comment by ConnysCode** [comment]
This should be a 1:1 representation of the current about command.

<img width="618" alt="image" src="https://github.com/xp-bot/xp-bot/assets/36863945/5b584d0c-d701-4863-8c3b-ee6458b8e943">
